server:
  port: 8760


spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://eureka
          predicates:
            - Path=/eureka/**
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - Jwt
        - id: demo2
          uri: lb://demo2
          predicates:
            - Path=/demo2/**
          filters:
            - StripPrefix=1
            - Jwt

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
          - refresh


security:
  jwtSecret: ThisIsASecret
  jwtExpiration: 3600000